# Generated by Django 4.2.6 on 2023-10-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockmodel",
            name="program_metrics",
            field=models.JSONField(default="Unknown", verbose_name="Program Metrics"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blockmodel",
            name="program_vardependencies",
            field=models.JSONField(default="{}", verbose_name="Dependency analysis"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blockmodel",
            name="program_variables",
            field=models.JSONField(default="{}", verbose_name="Program Variables"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blockmodel",
            name="program_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="reportmodel",
            name="check_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="reportmodel",
            name="check_verbose_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="reportmodel",
            name="report_content",
            field=models.TextField(),
        ),
    ]
