# Generated by Django 4.2.6 on 2023-10-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyser", "0002_blockmodel_program_metrics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportmodel",
            name="report_check_status",
            field=models.IntegerField(choices=[(0, "Fail"), (1, "Pass")], default=0),
        ),
        migrations.AddField(
            model_name="reportmodel",
            name="report_review_status",
            field=models.IntegerField(
                choices=[
                    (0, "Unviewed"),
                    (1, "Reviewed"),
                    (2, "Confirmed"),
                    (3, "False Positive"),
                ],
                default=0,
            ),
        ),
    ]
